# Generated by Django 2.1.8 on 2019-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatext',
            name='opt_title',
            field=models.CharField(blank=True, help_text='Is this a sub-title', max_length=100),
        ),
        migrations.AddField(
            model_name='qatext',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='qatext',
            name='qa_choice',
            field=models.CharField(choices=[('I', 'Introduction'), ('Q', 'Question'), ('S', 'Level 1'), ('2', 'Level II'), ('A', 'Answer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('INTRO', 'Introduction'), ('QUES', 'Question'), ('SUBQ', 'Level 1'), ('LEV2', 'Level 2')], default='QUES', max_length=5),
        ),
    ]
