# Generated by Django 2.1.8 on 2019-05-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_auto_20190519_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('personsid', models.CharField(blank=True, help_text='This is used for the html id field', max_length=10, null=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.AlterField(
            model_name='glossary',
            name='abbrev',
            field=models.CharField(choices=[('E', 'Entity'), ('A', 'Acronym')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='glossaryid',
            field=models.CharField(blank=True, default='#', help_text='This is used in the template id field', max_length=10, null=True),
        ),
    ]
