# Generated by Django 2.1.8 on 2019-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_glossary_abbrev_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
