# Generated by Django 2.1.8 on 2019-05-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_person_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatext',
            name='adobe_page',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
