# Generated by Django 2.1.8 on 2019-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0006_qatext_adobe_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, help_text='This will be auto-populated from the title field.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('INTRO', 'Introduction'), ('QUES', 'Question'), ('ABOUT', 'About'), ('SUBQ', 'Level 1'), ('LEV2', 'Level 2')], default='QUES', max_length=5),
        ),
    ]
