# Generated by Django 2.1.8 on 2019-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0007_auto_20190520_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='slug',
            field=models.SlugField(blank=True, help_text='This is the footnote number. The url will be volume/footnote', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='section',
            field=models.CharField(choices=[('VOL1', 'Volume I'), ('VOL2', 'Volume 2'), ('QUES', 'Questions')], help_text='What section of the report does this footnote belong to?', max_length=4),
        ),
    ]
